function [INFO] = feedback_train1(myWindow, INFO, itrial)

Report4 = 0;
while Report4 == 0
   response = DrawFormattedText(myWindow, INFO.P.text_instruction_feddback,...
        'center', INFO.P.screen.cy-500, [255, 255, 255, 255], [],[],[], 2);
    my_optimal_fixationpoint(myWindow, INFO.P.screen.cx, INFO.P.screen.cy,...
        INFO.P.stim.fixation_size, INFO.P.stim.fixation_square_color,...
        INFO.P.stim.background_color, INFO.P.screen.pixperdeg);
    Screen('Flip', myWindow);
    if button(INFO.P.setup.padh,2) == 1
        Report4 = 1;
    end
end



if INFO.T(itrial).button_probes_left == 1
    response_left = DrawFormattedText(myWindow, INFO.P.text_instruction_feddback_left,...
    'center', INFO.P.screen.cy-200, [255, 255, 255, 255], [],[],[], 2);
    my_optimal_fixationpoint(myWindow, INFO.P.screen.cx, INFO.P.screen.cy,...
        INFO.P.stim.fixation_size, INFO.P.stim.fixation_square_color, [0 128 0],...
        INFO.P.screen.pixperdeg)
    Screen('Flip', myWindow);
else
    response_left = DrawFormattedText(myWindow, INFO.P.text_instruction_feddback_left,...
        'center', INFO.P.screen.cy-200, [255, 255, 255, 255], [],[],[], 2);
    my_optimal_fixationpoint(myWindow, INFO.P.screen.cx, INFO.P.screen.cy,...
        INFO.P.stim.fixation_size, INFO.P.stim.fixation_square_color, [255 0 0],...
        INFO.P.screen.pixperdeg)
    Screen('Flip', myWindow);
end
WaitSecs(10)
if INFO.T(itrial).button_probes_right == 1
    response_right = DrawFormattedText(myWindow, INFO.P.text_instruction_feddback_right,...
        'center', INFO.P.screen.cy-200, [255, 255, 255, 255], [],[],[], 2);
    my_optimal_fixationpoint(myWindow, INFO.P.screen.cx, INFO.P.screen.cy,...
        INFO.P.stim.fixation_size, INFO.P.stim.fixation_square_color, [0 128 0],...
        INFO.P.screen.pixperdeg)
    Screen('Flip', myWindow);
else
    response_right = DrawFormattedText(myWindow, INFO.P.text_instruction_feddback_right,...
        'center', INFO.P.screen.cy-200, [255, 255, 255, 255], [],[],[], 2);
    my_optimal_fixationpoint(myWindow, INFO.P.screen.cx, INFO.P.screen.cy,...
        INFO.P.stim.fixation_size, INFO.P.stim.fixation_square_color, [255 0 0],...
        INFO.P.screen.pixperdeg)
    Screen('Flip', myWindow);
end
WaitSecs(10)
if INFO.T(itrial).button_attention == 0
    response_tilt = DrawFormattedText(myWindow, INFO.P.text_instruction_feddback_tilt,...
        'center', INFO.P.screen.cy-200, [255, 255, 255, 255], [],[],[], 2);
    my_optimal_fixationpoint(myWindow, INFO.P.screen.cx, INFO.P.screen.cy,...
        INFO.P.stim.fixation_size, INFO.P.stim.fixation_square_color, [0 128 0],...
        INFO.P.screen.pixperdeg)
    Screen('Flip', myWindow);
else
    response_tilt = DrawFormattedText(myWindow, INFO.P.text_instruction_feddback_tilt,...
        'center', INFO.P.screen.cy-200, [255, 255, 255, 255], [],[],[], 2);
    my_optimal_fixationpoint(myWindow, INFO.P.screen.cx, INFO.P.screen.cy,...
        INFO.P.stim.fixation_size, INFO.P.stim.fixation_square_color, [255 0 0],...
        INFO.P.screen.pixperdeg)
    Screen('Flip', myWindow);
end
WaitSecs(10)
