function [INFO, Correct_probes, Correct_attention] = response_validity (INFO, itrial)

% Yes/No detection task
if (INFO.T(itrial).probes == 1 & INFO.T(itrial).button_probes_right == 'y' & INFO.T(itrial).button_probes_left == 'n') ...
        || (INFO.T(itrial).probes == 2 & INFO.T(itrial).button_probes_right == 'n' & INFO.T(itrial).button_probes_left == 'y' )...
        || (INFO.T(itrial).probes == 3 & INFO.T(itrial).button_probes_right == 'y' & INFO.T(itrial).button_probes_left == 'y' )...
        || (INFO.T(itrial).probes == 4 & INFO.T(itrial).button_probes_right == 'n' & INFO.T(itrial).button_probes_left == 'n' )
    INFO.T(itrial).Correct_probes = 1
else
    INFO.T(itrial).Correct_probes = 0
end
Correct_probes = INFO.T(itrial).Correct_probes

% 2AFC discrimination task
if (INFO.T(itrial).attention == 1 & INFO.T(itrial).button_attention(1) == 'R')...
        || (INFO.T(itrial).attention == 2 & INFO.T(itrial).pre_cue == 1 & INFO.T(itrial).response_cue == 2 & INFO.T(itrial).button_attention(1) == 'L')...
        || (INFO.T(itrial).attention == 2 & INFO.T(itrial).pre_cue == 2 & INFO.T(itrial).response_cue == 1 & INFO.T(itrial).button_attention(1) == 'L')...
        || (INFO.T(itrial).attention == 2 & INFO.T(itrial).pre_cue == 1 & INFO.T(itrial).response_cue == 1 & INFO.T(itrial).button_attention(1) == 'R')...
        || (INFO.T(itrial).attention == 2 & INFO.T(itrial).pre_cue == 2 & INFO.T(itrial).response_cue == 2 & INFO.T(itrial).button_attention(1) == 'R')...
        || (INFO.T(itrial).attention == 3 & INFO.T(itrial).button_attention(1) == 'L')...
        || (INFO.T(itrial).attention == 4 & INFO.T(itrial).pre_cue == 1 & INFO.T(itrial).response_cue == 2 & INFO.T(itrial).button_attention(1) == 'R')...
        || (INFO.T(itrial).attention == 4 & INFO.T(itrial).pre_cue == 2 & INFO.T(itrial).response_cue == 1 & INFO.T(itrial).button_attention(1) == 'R')...
        || (INFO.T(itrial).attention == 4 & INFO.T(itrial).pre_cue == 1 & INFO.T(itrial).response_cue == 1 & INFO.T(itrial).button_attention(1) == 'L')...
        || (INFO.T(itrial).attention == 4 & INFO.T(itrial).pre_cue == 2 & INFO.T(itrial).response_cue == 2 & INFO.T(itrial).button_attention(1) == 'L')
    INFO.T(itrial).Correct_attention = 1
else
    INFO.T(itrial).Correct_attention = 0
end

Correct_attention = INFO.T(itrial).Correct_attention
    
    