% Test position targets
color = INFO.P.stim.background_color + (INFO.T(itrial).Contrast_probes * (255 - INFO.P.stim.background_color(1)));
location_probes_right_1 = INFO.P.position(2,1,:);
location_probes_left_1 = INFO.P.position(1,1,:);

location_probes_right_2 = INFO.P.position(2,2,:);
location_probes_left_2 = INFO.P.position(1,2,:);

location_probes_right_3 = INFO.P.position(2,3,:);
location_probes_left_3 = INFO.P.position(1,3,:);

location_probes_right_4 = INFO.P.position(2,4,:);
location_probes_left_4 = INFO.P.position(1,4,:);

location_probes_right_5 = INFO.P.position(2,5,:);
location_probes_left_5 = INFO.P.position(1,5,:);

location_attention_right_1 = INFO.P.position(2,1,:);
location_attention_left_1 = INFO.P.position(1,1,:);
rects_right_1 = [location_attention_right_1(1)-INFO.P.grating_tilt_width_pix/2;...
    location_attention_right_1(2)-INFO.P.grating_tilt_height_pix/2;...
    location_attention_right_1(1)+INFO.P.grating_tilt_width_pix/2;....
    location_attention_right_1(2)+INFO.P.grating_tilt_height_pix/2];
rects_left_1 = [location_attention_left_1(1)-INFO.P.grating_tilt_width_pix/2;...
    location_attention_left_1(2)-INFO.P.grating_tilt_height_pix/2;...
    location_attention_left_1(1)+INFO.P.grating_tilt_width_pix/2;....
    location_attention_left_1(2)+INFO.P.grating_tilt_height_pix/2];

location_attention_right_2 = INFO.P.position(2,2,:);
location_attention_left_2 = INFO.P.position(1,2,:);
rects_right_2 = [location_attention_right_2(1)-INFO.P.grating_tilt_width_pix/2;...
    location_attention_right_2(2)-INFO.P.grating_tilt_height_pix/2;...
    location_attention_right_2(1)+INFO.P.grating_tilt_width_pix/2;....
    location_attention_right_2(2)+INFO.P.grating_tilt_height_pix/2];
rects_left_2 = [location_attention_left_2(1)-INFO.P.grating_tilt_width_pix/2;...
    location_attention_left_2(2)-INFO.P.grating_tilt_height_pix/2;...
    location_attention_left_2(1)+INFO.P.grating_tilt_width_pix/2;....
    location_attention_left_2(2)+INFO.P.grating_tilt_height_pix/2];

location_attention_right_3 = INFO.P.position(2,3,:);
location_attention_left_3 = INFO.P.position(1,3,:);
rects_right_3 = [location_attention_right_3(1)-INFO.P.grating_tilt_width_pix/2;...
    location_attention_right_3(2)-INFO.P.grating_tilt_height_pix/2;...
    location_attention_right_3(1)+INFO.P.grating_tilt_width_pix/2;....
    location_attention_right_3(2)+INFO.P.grating_tilt_height_pix/2];
rects_left_3 = [location_attention_left_3(1)-INFO.P.grating_tilt_width_pix/2;...
    location_attention_left_3(2)-INFO.P.grating_tilt_height_pix/2;...
    location_attention_left_3(1)+INFO.P.grating_tilt_width_pix/2;....
    location_attention_left_3(2)+INFO.P.grating_tilt_height_pix/2];


location_attention_right_4 = INFO.P.position(2,4,:);
location_attention_left_4 = INFO.P.position(1,4,:);
rects_right_4 = [location_attention_right_4(1)-INFO.P.grating_tilt_width_pix/2;...
    location_attention_right_4(2)-INFO.P.grating_tilt_height_pix/2;...
    location_attention_right_4(1)+INFO.P.grating_tilt_width_pix/2;....
    location_attention_right_4(2)+INFO.P.grating_tilt_height_pix/2];
rects_left_4 = [location_attention_left_4(1)-INFO.P.grating_tilt_width_pix/2;...
    location_attention_left_4(2)-INFO.P.grating_tilt_height_pix/2;...
    location_attention_left_4(1)+INFO.P.grating_tilt_width_pix/2;....
    location_attention_left_4(2)+INFO.P.grating_tilt_height_pix/2];

location_attention_right_5 = INFO.P.position(2,5,:);
location_attention_left_5 = INFO.P.position(1,5,:);
rects_right_5 = [location_attention_right_5(1)-INFO.P.grating_tilt_width_pix/2;...
    location_attention_right_5(2)-INFO.P.grating_tilt_height_pix/2;...
    location_attention_right_5(1)+INFO.P.grating_tilt_width_pix/2;....
    location_attention_right_5(2)+INFO.P.grating_tilt_height_pix/2];
rects_left_5 = [location_attention_left_5(1)-INFO.P.grating_tilt_width_pix/2;...
    location_attention_left_5(2)-INFO.P.grating_tilt_height_pix/2;...
    location_attention_left_5(1)+INFO.P.grating_tilt_width_pix/2;....
    location_attention_left_5(2)+INFO.P.grating_tilt_height_pix/2];


Screen('BlendFunction', myWindow, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
Screen('DrawDots', myWindow, [location_probes_right_1(1) location_probes_right_1(2)], INFO.P.circle_detection_size_pix, color, [], 2);

Screen('DrawDots', myWindow, [location_probes_left_1(1) location_probes_left_1(2)], INFO.P.circle_detection_size_pix, color, [], 2);

Screen('DrawDots', myWindow, [location_probes_right_2(1) location_probes_right_2(2)], INFO.P.circle_detection_size_pix, color, [], 2);

Screen('DrawDots', myWindow, [location_probes_left_2(1) location_probes_left_2(2)], INFO.P.circle_detection_size_pix, color, [], 2);

Screen('DrawDots', myWindow, [location_probes_right_3(1) location_probes_right_3(2)], INFO.P.circle_detection_size_pix, color, [], 2);

Screen('DrawDots', myWindow, [location_probes_left_3(1) location_probes_left_3(2)], INFO.P.circle_detection_size_pix, color, [], 2);

Screen('DrawDots', myWindow, [location_probes_right_4(1) location_probes_right_4(2)], INFO.P.circle_detection_size_pix, color, [], 2);

Screen('DrawDots', myWindow, [location_probes_left_4(1) location_probes_left_4(2)], INFO.P.circle_detection_size_pix, color, [], 2);

Screen('DrawDots', myWindow, [location_probes_right_5(1) location_probes_right_5(2)], INFO.P.circle_detection_size_pix, color, [], 2);

Screen('DrawDots', myWindow, [location_probes_left_5(1) location_probes_left_5(2)], INFO.P.circle_detection_size_pix, color, [], 2);


Screen('DrawTexture', myWindow, gabortex, [], [rects_right_1],...
    -rad2deg(INFO.T(itrial).Contrast_attention), [], [], [], [], kPsychDontDoRotation,...
    [INFO.P.grating_tilt_phase+180, INFO.P.grating_tilt_freq, INFO.P.grating_tilt_sc,...
    INFO.P.grating_tilt_contrast, INFO.P.grating_tilt_aspectratio, 0, 0, 0]);

Screen('DrawTexture', myWindow, gabortex, [], [rects_right_2],...
    -rad2deg(INFO.T(itrial).Contrast_attention), [], [], [], [], kPsychDontDoRotation,...
    [INFO.P.grating_tilt_phase+180, INFO.P.grating_tilt_freq, INFO.P.grating_tilt_sc,...
    INFO.P.grating_tilt_contrast, INFO.P.grating_tilt_aspectratio, 0, 0, 0]);

Screen('DrawTexture', myWindow, gabortex, [], [rects_right_3],...
    -rad2deg(INFO.T(itrial).Contrast_attention), [], [], [], [], kPsychDontDoRotation,...
    [INFO.P.grating_tilt_phase+180, INFO.P.grating_tilt_freq, INFO.P.grating_tilt_sc,...
    INFO.P.grating_tilt_contrast, INFO.P.grating_tilt_aspectratio, 0, 0, 0]);

Screen('DrawTexture', myWindow, gabortex, [], [rects_right_4],...
    -rad2deg(INFO.T(itrial).Contrast_attention), [], [], [], [], kPsychDontDoRotation,...
    [INFO.P.grating_tilt_phase+180, INFO.P.grating_tilt_freq, INFO.P.grating_tilt_sc,...
    INFO.P.grating_tilt_contrast, INFO.P.grating_tilt_aspectratio, 0, 0, 0]);

Screen('DrawTexture', myWindow, gabortex, [], [rects_right_5],...
    -rad2deg(INFO.T(itrial).Contrast_attention), [], [], [], [], kPsychDontDoRotation,...
    [INFO.P.grating_tilt_phase+180, INFO.P.grating_tilt_freq, INFO.P.grating_tilt_sc,...
    INFO.P.grating_tilt_contrast, INFO.P.grating_tilt_aspectratio, 0, 0, 0]);

Screen('DrawTexture', myWindow, gabortex, [], [rects_left_1],...
    -rad2deg(INFO.T(itrial).Contrast_attention), [], [], [], [], kPsychDontDoRotation,...
    [INFO.P.grating_tilt_phase+180, INFO.P.grating_tilt_freq, INFO.P.grating_tilt_sc,...
    INFO.P.grating_tilt_contrast, INFO.P.grating_tilt_aspectratio, 0, 0, 0]);

Screen('DrawTexture', myWindow, gabortex, [], [rects_left_2],...
    -rad2deg(INFO.T(itrial).Contrast_attention), [], [], [], [], kPsychDontDoRotation,...
    [INFO.P.grating_tilt_phase+180, INFO.P.grating_tilt_freq, INFO.P.grating_tilt_sc,...
    INFO.P.grating_tilt_contrast, INFO.P.grating_tilt_aspectratio, 0, 0, 0]);

Screen('DrawTexture', myWindow, gabortex, [], [rects_left_3],...
    -rad2deg(INFO.T(itrial).Contrast_attention), [], [], [], [], kPsychDontDoRotation,...
    [INFO.P.grating_tilt_phase+180, INFO.P.grating_tilt_freq, INFO.P.grating_tilt_sc,...
    INFO.P.grating_tilt_contrast, INFO.P.grating_tilt_aspectratio, 0, 0, 0]);

Screen('DrawTexture', myWindow, gabortex, [], [rects_left_4],...
    -rad2deg(INFO.T(itrial).Contrast_attention), [], [], [], [], kPsychDontDoRotation,...
    [INFO.P.grating_tilt_phase+180, INFO.P.grating_tilt_freq, INFO.P.grating_tilt_sc,...
    INFO.P.grating_tilt_contrast, INFO.P.grating_tilt_aspectratio, 0, 0, 0]);

Screen('DrawTexture', myWindow, gabortex, [], [rects_left_5],...
    -rad2deg(INFO.T(itrial).Contrast_attention), [], [], [], [], kPsychDontDoRotation,...
    [INFO.P.grating_tilt_phase+180, INFO.P.grating_tilt_freq, INFO.P.grating_tilt_sc,...
    INFO.P.grating_tilt_contrast, INFO.P.grating_tilt_aspectratio, 0, 0, 0]);

Screen('Flip',myWindow)               